const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const base=process.env.TEST_URL||'http://127.0.0.1:4318';
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
const platform=process.env.TEST_PLATFORM||'ios';const device=process.env.TEST_DEVICE || await page.locator('#device option').evaluateAll((options, platform)=>options.find(o=>o.textContent.includes(platform==='ios'?'BugDrop-Test':'ANDROID'))?.value,platform);
assert.ok(device,'Start the BugDrop-Test simulator or set TEST_DEVICE.');
await page.selectOption('#device',device);await page.waitForFunction(()=>[...document.querySelector('#app').options].some(o=>o.value==='xyz.aimo.bugdrop.demo'),{},{timeout:30000});await page.selectOption('#app','xyz.aimo.bugdrop.demo');await page.check('#video');await page.click('#start');await page.waitForFunction(()=>document.querySelector('#badge').textContent.includes('Recording'),{},{timeout:30000}).catch(async e=>{throw new Error(e.message+' UI: '+await page.locator('#error').textContent()+' STATUS: '+await page.locator('#output').textContent());});
await page.click('#shot');await page.fill('#note','Tapped checkout; an HTTP 503 error appeared.');await page.click('#add-note');await page.waitForFunction(()=>document.querySelector('#output').textContent.includes('Screenshot saved'),{},{timeout:25000});
await page.screenshot({path:'test-results/desktop-'+platform+'.png',fullPage:true});await page.click('#stop');await page.waitForFunction(()=>!document.querySelector('#review').hidden,{},{timeout:30000});
const reviewUrl=await page.locator('#review').getAttribute('href');const review=await browser.newPage();await review.goto(base+reviewUrl);await review.waitForFunction(()=>document.querySelector('video')?.readyState>=1);await review.fill('#expected','Open payment screen.');await review.fill('#actual','Checkout fails with HTTP 503.');await review.check('#reviewed');const download=review.waitForEvent('download');await review.click('#json');await(await download).saveAs('test-results/desktop-'+platform+'.json');const r=JSON.parse(fs.readFileSync('test-results/desktop-'+platform+'.json'));assert.ok(r.events.some(e=>e.message.includes('503')));assert.ok(r.events.some(e=>e.kind==='console'&&e.message.includes('503')),'actual app log');assert.equal(r.artifacts.length,2);assert.ok(!JSON.stringify(r.events).includes('synthetic-secret'));assert.ok(!JSON.stringify(r.events).includes('sample@example.com'));assert.equal(errors.length,0);
// Review is mandatory; edits reset consent, and deselected evidence stays out of exports.
await review.fill('#actual','Updated observation');assert.ok(await review.locator('#json').isDisabled());
const first=review.locator('#events input').first();await first.uncheck();await review.check('#reviewed');
const mdDownload=review.waitForEvent('download');await review.click('#md');await(await mdDownload).saveAs('test-results/desktop-'+platform+'.md');assert.ok(fs.readFileSync('test-results/desktop-'+platform+'.md','utf8').includes('Updated observation'));
const oldTitle=await review.locator('#title').inputValue();
await page.click('#start');await page.waitForFunction(()=>document.querySelector('#badge').textContent.includes('Recording'),{},{timeout:30000}).catch(async e=>{throw new Error(e.message+' UI: '+await page.locator('#error').textContent()+' STATUS: '+await page.locator('#output').textContent());});await page.click('#stop');await page.waitForFunction(()=>!document.querySelector('#review').hidden,{},{timeout:30000});
assert.notEqual(await page.locator('#review').getAttribute('href'),reviewUrl,'unique capture URL');
await review.reload();assert.equal(await review.locator('#title').inputValue(),oldTitle,'old report stays accessible');
console.log('PASS desktop '+platform+': app discovery, recording, screenshot, logs, redaction, stop, video playback, reviewed JSON export');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
