const $=id=>document.getElementById(id);const token=document.querySelector('meta[name="bugdrop-token"]').content;let busy=false,state={},generation=0;
async function api(route,body){const res=await fetch('/api/'+route,{method:body?'POST':'GET',headers:{'X-BugDrop-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
async function safe(fn){$('error').hidden=true;try{await fn();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}}
function options(id,items,empty){$(id).replaceChildren();const first=document.createElement('option');first.value='';first.textContent=empty;$(id).append(first);for(const item of items){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;$(id).append(option);}}
function update(){const running=!!state.recording,locked=running||state.starting||state.pending||busy;$('start').disabled=locked||!$('app').value;$('start').hidden=running;$('stop').hidden=!running;for(const id of ['device','app','refresh','video'])$(id).disabled=locked;for(const id of ['shot','note','add-note'])$(id).disabled=!running;$('badge').textContent=running?'● Recording':state.starting?'Starting…':state.report?.endedAt?'Report ready':'Ready';$('badge').classList.toggle('recording',running);$('output').textContent=state.output||'Your capture status will appear here.';$('count').textContent=state.report?state.report.events.length+' EVENTS SAVED':'NO CAPTURE YET';$('review').hidden=!state.review;if(state.review)$('review').href=state.review;$('location').textContent=state.dir||'';}
async function refresh(){const n=++generation;busy=true;update();try{const data=await api('devices');if(n!==generation)return;options('device',data.devices.map(d=>({...d,name:d.name+' · '+d.platform.toUpperCase()})),data.devices.length?'Choose a device':'No running devices — start a simulator');options('app',[],'Choose a device first');$('warnings').textContent=data.warnings.join(' ');}finally{busy=false;update();}}
$('refresh').onclick=()=>safe(refresh);
$('device').onchange=()=>safe(async()=>{const n=++generation;options('app',[],'Loading apps…');busy=true;update();try{if(!$('device').value)return;const apps=await api('apps?device='+encodeURIComponent($('device').value));if(n===generation)options('app',apps,apps.length?'Choose your app':'No eligible apps found');}finally{busy=false;update();}});
$('app').onchange=update;
$('start').onclick=()=>safe(async()=>{busy=true;update();try{await api('start',{device:$('device').value,app:$('app').value,video:$('video').checked});state=await api('state');}finally{busy=false;update();}});
$('stop').onclick=()=>safe(async()=>{await api('stop',{});$('stop').disabled=true;});
$('shot').onclick=()=>safe(async()=>{await api('screenshot',{});});
$('add-note').onclick=()=>safe(async()=>{if(!$('note').value.trim())return;await api('note',{text:$('note').value});$('note').value='';});
safe(refresh);setInterval(async()=>{try{state=await api('state');if(!state.recording)$('stop').disabled=false;update();}catch(e){$('error').textContent=e.message;$('error').hidden=false;}},1500);
